#!/usr/bin/env node
// build-release.mjs — 打包构建脚本
//
// 构建流程：
//   1. vite build 前端 → packages/web/dist
//   2. esbuild bundle 后端（含 workspace 扩展包）→ dist-release/server/index.js
//   3. 拷贝前端产物 → dist-release/public
//   4. 生成 dist-release/package.json + bin/myagent.js
//
// 用法：node scripts/build-release.mjs

import { build } from "esbuild";
import { execSync } from "child_process";
import { cpSync, rmSync, mkdirSync, writeFileSync, existsSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const releaseDir = resolve(root, "dist-release");

const STEP = "\n  ▸";

// ─── Step 0: 清理 ───
console.log(`${STEP} 清理 dist-release/ ...`);
rmSync(releaseDir, { recursive: true, force: true });
mkdirSync(resolve(releaseDir, "server"), { recursive: true });
mkdirSync(resolve(releaseDir, "bin"), { recursive: true });

// ─── Step 1: 前端构建 ───
console.log(`${STEP} 构建前端 (vite build) ...`);
execSync("pnpm --filter web build", { cwd: root, stdio: "inherit" });

// ─── Step 2: 拷贝前端产物 ───
console.log(`${STEP} 拷贝前端产物 → dist-release/public/ ...`);
cpSync(
  resolve(root, "packages", "web", "dist"),
  resolve(releaseDir, "public"),
  { recursive: true },
);

// ─── Step 3: esbuild bundle 后端 ───
console.log(`${STEP} esbuild bundle 后端 ...`);
await build({
  entryPoints: [resolve(root, "packages", "server", "src", "index.ts")],
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  outfile: resolve(releaseDir, "server", "index.js"),
  // 这些是 npm 上的运行时依赖，保持外部引用（从 node_modules 解析）
  external: [
    "fastify",
    "@fastify/cors",
    "@fastify/static",
    "@fastify/websocket",
    "@earendil-works/pi-ai",
    "@earendil-works/pi-coding-agent",
    "@modelcontextprotocol/sdk",
    "dotenv",
    "ws",
    "cors",
    "pino",       // fastify 的日志依赖
    "json-schema", // fastify 校验
  ],
  banner: {
    js: '// MyAgent Server — auto-generated by build-release.mjs\n// 外部依赖从 node_modules 解析，workspace 扩展包已内联',
  },
  logLevel: "info",
});

// ─── Step 4: 生成 bin 入口 ───
console.log(`${STEP} 生成 bin/myagent.js ...`);
writeFileSync(
  resolve(releaseDir, "bin", "myagent.js"),
  `#!/usr/bin/env node
// myagent CLI 入口
// 启动后端服务器（同时托管前端）

import { spawn } from "child_process";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const serverFile = resolve(__dirname, "..", "server", "index.js");

// 解析命令行参数
const args = process.argv.slice(2);
const portFlag = args.find(a => a.startsWith("--port="));
if (portFlag) {
  process.env.PORT = portFlag.split("=")[1];
}

// 直接 import server（同一进程）
await import(serverFile);
`,
  { mode: 0o755 },
);

// ─── Step 5: 生成 package.json ───
console.log(`${STEP} 生成 dist-release/package.json ...`);
writeFileSync(
  resolve(releaseDir, "package.json"),
  JSON.stringify({
    name: "myagent",
    version: "0.1.0",
    description: "MyAgent — AI Agent with web UI",
    type: "module",
    bin: {
      myagent: "./bin/myagent.js",
    },
    files: [
      "bin/",
      "server/",
      "public/",
    ],
    engines: {
      node: ">=18",
    },
    dependencies: {
      "fastify": "^5.2.1",
      "@fastify/cors": "^11.0.1",
      "@fastify/static": "^8.0.0",
      "@fastify/websocket": "^11.0.2",
      "@earendil-works/pi-ai": "^0.80.6",
      "@earendil-works/pi-coding-agent": "latest",
      "@modelcontextprotocol/sdk": "^1.29.0",
      "dotenv": "^17.4.2",
      "ws": "^8.21.0",
    },
  }, null, 2) + "\n",
);

console.log(`
  ✓ 构建完成！

  dist-release/
    bin/myagent.js       ← CLI 入口
    server/index.js      ← 后端 bundle
    public/              ← 前端静态文件
    package.json

  下一步：
    cd dist-release && npm pack        # 生成 .tgz
    npm install -g ./myagent-0.1.0.tgz  # 本地安装
    myagent                             # 启动 → http://localhost:3000
`);
